"""add anzahl to ding

Revision ID: 2b45641f845b
Revises: ebae54d51809
Create Date: 2026-03-03 07:50:08.729016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b45641f845b'
down_revision = 'ebae54d51809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anzahl', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ding', schema=None) as batch_op:
        batch_op.drop_column('anzahl')

    # ### end Alembic commands ###
