"""behaelter gestell_id

Revision ID: 3af070b719b5
Revises: 3c844f41149e
Create Date: 2026-02-23 13:15:11.905058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af070b719b5'
down_revision = '3c844f41149e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('behaelter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gestell_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'gestell', ['gestell_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('behaelter', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('gestell_id')

    # ### end Alembic commands ###
