"""initiales Schema

Revision ID: 3c844f41149e
Revises: 
Create Date: 2026-02-23 11:11:31.657232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c844f41149e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('qr_code', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_code')
    )
    op.create_table('raum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('qr_code', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_code')
    )
    op.create_table('gestell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raum_id', sa.Integer(), nullable=False),
    sa.Column('typ', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('qr_code', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['raum_id'], ['raum.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_code')
    )
    op.create_table('regalfach',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gestell_id', sa.Integer(), nullable=False),
    sa.Column('bezeichnung', sa.String(length=100), nullable=False),
    sa.Column('position_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gestell_id'], ['gestell.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('behaelter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typ', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('regalfach_id', sa.Integer(), nullable=True),
    sa.Column('raum_id', sa.Integer(), nullable=True),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('qr_code', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['raum_id'], ['raum.id'], ),
    sa.ForeignKeyConstraint(['regalfach_id'], ['regalfach.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_code')
    )
    op.create_table('ding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('raum_id', sa.Integer(), nullable=True),
    sa.Column('regalfach_id', sa.Integer(), nullable=True),
    sa.Column('behaelter_id', sa.Integer(), nullable=True),
    sa.Column('kategorie_id', sa.Integer(), nullable=True),
    sa.Column('hersteller', sa.String(length=200), nullable=True),
    sa.Column('modell', sa.String(length=200), nullable=True),
    sa.Column('seriennummer', sa.String(length=200), nullable=True),
    sa.Column('kaufdatum', sa.Date(), nullable=True),
    sa.Column('kaufpreis', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('waehrung', sa.String(length=10), nullable=True),
    sa.Column('garantie_bis', sa.Date(), nullable=True),
    sa.Column('versichert_bei', sa.String(length=200), nullable=True),
    sa.Column('versicherungsnummer', sa.String(length=200), nullable=True),
    sa.Column('qr_code', sa.String(length=100), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['behaelter_id'], ['behaelter.id'], ),
    sa.ForeignKeyConstraint(['kategorie_id'], ['kategorie.id'], ),
    sa.ForeignKeyConstraint(['raum_id'], ['raum.id'], ),
    sa.ForeignKeyConstraint(['regalfach_id'], ['regalfach.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_code')
    )
    op.create_table('bewegung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ding_id', sa.Integer(), nullable=False),
    sa.Column('von_beschreibung', sa.String(length=500), nullable=True),
    sa.Column('nach_beschreibung', sa.String(length=500), nullable=True),
    sa.Column('zeitpunkt', sa.DateTime(), nullable=True),
    sa.Column('notiz', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ding_id'], ['ding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ding_tag',
    sa.Column('ding_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ding_id'], ['ding.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('ding_id', 'tag_id')
    )
    op.create_table('medium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ding_id', sa.Integer(), nullable=False),
    sa.Column('typ', sa.String(length=20), nullable=False),
    sa.Column('dateiname', sa.String(length=255), nullable=True),
    sa.Column('pfad', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('hochgeladen_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ding_id'], ['ding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verleih',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ding_id', sa.Integer(), nullable=False),
    sa.Column('person', sa.String(length=200), nullable=False),
    sa.Column('ausgeliehen_am', sa.Date(), nullable=False),
    sa.Column('faellig_am', sa.Date(), nullable=True),
    sa.Column('zurueck_am', sa.Date(), nullable=True),
    sa.Column('notiz', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ding_id'], ['ding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verleih')
    op.drop_table('medium')
    op.drop_table('ding_tag')
    op.drop_table('bewegung')
    op.drop_table('ding')
    op.drop_table('behaelter')
    op.drop_table('regalfach')
    op.drop_table('gestell')
    op.drop_table('raum')
    op.drop_table('zone')
    op.drop_table('tag')
    op.drop_table('kategorie')
    # ### end Alembic commands ###
