"""bewegung fuer behaelter und gestell

Revision ID: 9845f4297360
Revises: 2b45641f845b
Create Date: 2026-03-03 10:37:35.521533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9845f4297360'
down_revision = '2b45641f845b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bewegung', schema=None) as batch_op:
        batch_op.add_column(sa.Column('behaelter_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gestell_id', sa.Integer(), nullable=True))
        batch_op.alter_column('ding_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'behaelter', ['behaelter_id'], ['id'])
        batch_op.create_foreign_key(None, 'gestell', ['gestell_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bewegung', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('ding_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('gestell_id')
        batch_op.drop_column('behaelter_id')

    # ### end Alembic commands ###
